'use client';

import { BusinessInsights, Language } from '@/lib/types';

interface ExportPDFProps {
  insights: BusinessInsights;
  language: Language;
}

export default function ExportPDF({ insights, language }: ExportPDFProps) {
  const handleExport = async () => {
    // Dynamic import to reduce bundle size
    const jsPDF = (await import('jspdf')).default;

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    let yPos = 20;

    // Title
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    const title =
      language === 'hi'
        ? 'व्यापार AI - व्यवसाय स्वास्थ्य रिपोर्ट'
        : language === 'mr'
        ? 'व्यापार AI - व्यवसाय आरोग्य अहवाल'
        : 'Vyapar AI - Business Health Report';
    doc.text(title, pageWidth / 2, yPos, { align: 'center' });
    yPos += 15;

    // Date
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    const date = new Date().toLocaleDateString();
    doc.text(`Date: ${date}`, pageWidth / 2, yPos, { align: 'center' });
    yPos += 15;

    // Helper function to add section
    const addSection = (title: string, content: string | string[]) => {
      if (yPos > 250) {
        doc.addPage();
        yPos = 20;
      }

      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text(title, 20, yPos);
      yPos += 8;

      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');

      if (Array.isArray(content)) {
        content.forEach((item) => {
          const lines = doc.splitTextToSize(item, pageWidth - 40);
          lines.forEach((line: string) => {
            if (yPos > 280) {
              doc.addPage();
              yPos = 20;
            }
            doc.text(`• ${line}`, 25, yPos);
            yPos += 6;
          });
        });
      } else {
        const lines = doc.splitTextToSize(content, pageWidth - 40);
        lines.forEach((line: string) => {
          if (yPos > 280) {
            doc.addPage();
            yPos = 20;
          }
          doc.text(line, 20, yPos);
          yPos += 6;
        });
      }
      yPos += 5;
    };

    // Add sections
    const sections = {
      en: {
        profit: 'True Profit Analysis',
        products: 'Loss-Making Products',
        inventory: 'Blocked Inventory Cash',
        expenses: 'Abnormal Expenses',
        cashflow: '7-Day Cashflow Forecast',
      },
      hi: {
        profit: 'असली लाभ विश्लेषण',
        products: 'नुकसान देने वाले उत्पाद',
        inventory: 'फंसा हुआ इन्वेंटरी कैश',
        expenses: 'असामान्य खर्चे',
        cashflow: '7-दिन का कैशफ्लो पूर्वानुमान',
      },
      mr: {
        profit: 'खरा नफा विश्लेषण',
        products: 'तोटा देणारी उत्पादने',
        inventory: 'अडकलेली इन्व्हेंटरी रोख',
        expenses: 'असामान्य खर्च',
        cashflow: '7-दिवसांचा कॅशफ्लो अंदाज',
      },
    };

    const labels = sections[language];

    addSection(labels.profit, insights.trueProfitAnalysis);
    addSection(labels.products, insights.lossMakingProducts);
    addSection(labels.inventory, insights.blockedInventoryCash);
    addSection(labels.expenses, insights.abnormalExpenses);
    addSection(labels.cashflow, insights.cashflowForecast);

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(128);
    const footer =
      language === 'hi'
        ? 'व्यापार AI द्वारा उत्पन्न - आपके व्यवसाय के लिए AI-संचालित अंतर्दृष्टि'
        : language === 'mr'
        ? 'व्यापार AI द्वारे तयार - तुमच्या व्यवसायासाठी AI-चालित अंतर्दृष्टि'
        : 'Generated by Vyapar AI - AI-powered insights for your business';
    doc.text(footer, pageWidth / 2, 285, { align: 'center' });

    // Save
    const filename =
      language === 'hi'
        ? 'व्यापार-रिपोर्ट.pdf'
        : language === 'mr'
        ? 'व्यापार-अहवाल.pdf'
        : 'vyapar-report.pdf';
    doc.save(filename);
  };

  const buttonText =
    language === 'hi'
      ? '📄 PDF डाउनलोड करें'
      : language === 'mr'
      ? '📄 PDF डाउनलोड करा'
      : '📄 Download PDF Report';

  return (
    <button
      onClick={handleExport}
      className="w-full bg-red-500 text-white py-3 px-6 rounded-lg font-semibold hover:bg-red-600 transition-colors shadow-lg hover:shadow-xl flex items-center justify-center gap-2"
    >
      <span className="text-2xl">📥</span>
      <span>{buttonText}</span>
    </button>
  );
}
