'use client';

import { BenchmarkData, BusinessInsights, Language, SeverityLevel } from '@/lib/types';
import { Button } from './ui/Button';

interface ExportPDFProps {
  insights: BusinessInsights;
  language: Language;
  benchmark?: BenchmarkData | null;
}

type Labels = {
  title: string;
  subtitle: string;
  generatedOn: string;
  alerts: string;
  recommendations: string;
  visualAnalysis: string;
  benchmark: string;
  insights: string;
  sections: {
    profit: string;
    products: string;
    inventory: string;
    expenses: string;
    cashflow: string;
  };
  severity: Record<SeverityLevel, string>;
  benchmarkLabels: {
    yourBusiness: string;
    industryAverage: string;
    topPerformers: string;
  };
  footer: string;
  pageLabel: string;
  noData: string;
  buttonText: string;
};

const LABELS: Record<Language, Labels> = {
  en: {
    title: 'Vyapar AI Business Analysis Report',
    subtitle: 'Structured report generated from smart alerts, recommendations, charts, benchmark, and business insights.',
    generatedOn: 'Generated on',
    alerts: 'Smart Alerts',
    recommendations: 'Actionable Recommendations',
    visualAnalysis: 'Visual Analysis',
    benchmark: 'Business Benchmark',
    insights: 'Business Insights',
    sections: {
      profit: 'True Profit',
      products: 'Loss-Making Products',
      inventory: 'Blocked Cash in Inventory',
      expenses: 'Unusual Expenses',
      cashflow: '7-Day Cashflow Forecast',
    },
    severity: {
      critical: 'Critical',
      warning: 'Needs attention',
      good: 'Healthy',
      info: 'Informational',
    },
    benchmarkLabels: {
      yourBusiness: 'Your Business',
      industryAverage: 'Similar Businesses',
      topPerformers: 'Top Performers',
    },
    footer: 'Generated by Vyapar AI',
    pageLabel: 'Page',
    noData: 'No data available',
    buttonText: '📄 Download PDF Report',
  },
  hi: {
    title: 'Vyapar AI व्यवसाय विश्लेषण रिपोर्ट',
    subtitle: 'स्मार्ट अलर्ट, सिफारिशें, चार्ट, बेंचमार्क और बिज़नेस इनसाइट्स पर आधारित रिपोर्ट।',
    generatedOn: 'तैयार किया गया',
    alerts: 'स्मार्ट अलर्ट',
    recommendations: 'कार्रवाई योग्य सिफारिशें',
    visualAnalysis: 'विज़ुअल विश्लेषण',
    benchmark: 'व्यवसाय बेंचमार्क',
    insights: 'व्यवसाय इनसाइट्स',
    sections: {
      profit: 'असली लाभ',
      products: 'नुकसान देने वाले उत्पाद',
      inventory: 'इन्वेंटरी में फंसा कैश',
      expenses: 'असामान्य खर्च',
      cashflow: '7-दिन का कैशफ्लो पूर्वानुमान',
    },
    severity: {
      critical: 'गंभीर',
      warning: 'ध्यान देने योग्य',
      good: 'स्वस्थ',
      info: 'सामान्य जानकारी',
    },
    benchmarkLabels: {
      yourBusiness: 'आपका व्यवसाय',
      industryAverage: 'समान व्यवसाय',
      topPerformers: 'बेहतर प्रदर्शन करने वाले',
    },
    footer: 'Vyapar AI द्वारा तैयार',
    pageLabel: 'पृष्ठ',
    noData: 'डेटा उपलब्ध नहीं है',
    buttonText: '📄 PDF डाउनलोड करें',
  },
  mr: {
    title: 'Vyapar AI व्यवसाय विश्लेषण अहवाल',
    subtitle: 'स्मार्ट अलर्ट, शिफारसी, चार्ट, बेंचमार्क आणि व्यवसाय इनसाइट्सवर आधारित अहवाल.',
    generatedOn: 'तयार केले',
    alerts: 'स्मार्ट अलर्ट',
    recommendations: 'कृतीयोग्य शिफारसी',
    visualAnalysis: 'व्हिज्युअल विश्लेषण',
    benchmark: 'व्यवसाय बेंचमार्क',
    insights: 'व्यवसाय इनसाइट्स',
    sections: {
      profit: 'खरा नफा',
      products: 'तोटा देणारी उत्पादने',
      inventory: 'इन्व्हेंटरीमध्ये अडकलेली रोख',
      expenses: 'असामान्य खर्च',
      cashflow: '7-दिवसांचा रोख प्रवाह अंदाज',
    },
    severity: {
      critical: 'गंभीर',
      warning: 'लक्ष देण्यासारखे',
      good: 'चांगली स्थिती',
      info: 'माहितीपूर्ण',
    },
    benchmarkLabels: {
      yourBusiness: 'तुमचा व्यवसाय',
      industryAverage: 'समान व्यवसाय',
      topPerformers: 'उत्कृष्ट कामगिरी करणारे',
    },
    footer: 'Vyapar AI द्वारे तयार',
    pageLabel: 'पृष्ठ',
    noData: 'डेटा उपलब्ध नाही',
    buttonText: '📄 PDF डाउनलोड करा',
  },
};

const CHART_COLORS = ['#3b82f6', '#10b981', '#f59e0b', '#8b5cf6', '#ef4444', '#06b6d4', '#f97316'];

function clean(text: string): string {
  return text.replace(/[*_`#>]/g, '').replace(/\s+/g, ' ').trim();
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function truncate(text: string, max: number): string {
  const normalized = clean(text);
  if (normalized.length <= max) return normalized;
  const cut = normalized.slice(0, max);
  const wordBreak = cut.lastIndexOf(' ');
  return `${cut.slice(0, wordBreak > 0 ? wordBreak : max).trim()}...`;
}

function severityStyle(severity: SeverityLevel | undefined) {
  switch (severity) {
    case 'critical':
      return { bg: '#fef2f2', border: '#fecaca', text: '#dc2626' };
    case 'warning':
      return { bg: '#fffbeb', border: '#fde68a', text: '#d97706' };
    case 'good':
      return { bg: '#f0fdf4', border: '#bbf7d0', text: '#16a34a' };
    default:
      return { bg: '#eff6ff', border: '#bfdbfe', text: '#2563eb' };
  }
}

function renderLineChart(title: string, labels: string[], values: number[]): string {
  if (!values.length) return '';
  const width = 360;
  const height = 210;
  const chartLeft = 36;
  const chartTop = 18;
  const chartWidth = 300;
  const chartHeight = 130;
  const max = Math.max(...values);
  const min = Math.min(...values);
  const range = max - min || 1;
  const points = values
    .map((value, index) => {
      const x = chartLeft + (index / Math.max(values.length - 1, 1)) * chartWidth;
      const y = chartTop + chartHeight - ((value - min) / range) * chartHeight;
      return `${x},${y}`;
    })
    .join(' ');

  const xLabels = labels.slice(-5).map((label, index, arr) => {
    const x = chartLeft + (index / Math.max(arr.length - 1, 1)) * chartWidth;
    return `<text x="${x}" y="${chartTop + chartHeight + 18}" font-size="9" fill="#64748b" text-anchor="middle">${escapeHtml(label.slice(5))}</text>`;
  });

  return `
    <div class="chart-card">
      <div class="chart-title">${escapeHtml(title)}</div>
      <svg viewBox="0 0 ${width} ${height}" class="chart-svg">
        <line x1="${chartLeft}" y1="${chartTop + chartHeight}" x2="${chartLeft + chartWidth}" y2="${chartTop + chartHeight}" stroke="#cbd5e1" stroke-width="1"/>
        <line x1="${chartLeft}" y1="${chartTop}" x2="${chartLeft}" y2="${chartTop + chartHeight}" stroke="#cbd5e1" stroke-width="1"/>
        <polyline fill="none" stroke="#3b82f6" stroke-width="3" points="${points}" />
        ${points
          .split(' ')
          .map((point) => {
            const [x, y] = point.split(',');
            return `<circle cx="${x}" cy="${y}" r="3.5" fill="#ffffff" stroke="#3b82f6" stroke-width="2"/>`;
          })
          .join('')}
        ${xLabels.join('')}
      </svg>
    </div>`;
}

function renderVerticalBars(title: string, labels: string[], values: number[], color: string): string {
  if (!values.length) return '';
  const width = 360;
  const height = 210;
  const chartLeft = 28;
  const chartTop = 18;
  const chartWidth = 316;
  const chartHeight = 122;
  const max = Math.max(...values) || 1;
  const barWidth = Math.max(18, Math.floor(chartWidth / Math.max(values.length, 1)) - 10);

  const bars = values.slice(0, 6).map((value, index) => {
    const x = chartLeft + index * (barWidth + 12);
    const barHeight = (value / max) * chartHeight;
    const y = chartTop + chartHeight - barHeight;
    const label = truncate(labels[index] || '', 14);
    return `
      <rect x="${x}" y="${y}" width="${barWidth}" height="${barHeight}" rx="4" fill="${color}" />
      <text x="${x + barWidth / 2}" y="${chartTop + chartHeight + 14}" font-size="8.5" fill="#64748b" text-anchor="middle">${escapeHtml(label)}</text>
    `;
  });

  return `
    <div class="chart-card">
      <div class="chart-title">${escapeHtml(title)}</div>
      <svg viewBox="0 0 ${width} ${height}" class="chart-svg">
        <line x1="${chartLeft}" y1="${chartTop + chartHeight}" x2="${chartLeft + chartWidth}" y2="${chartTop + chartHeight}" stroke="#cbd5e1" stroke-width="1"/>
        ${bars.join('')}
      </svg>
    </div>`;
}

function renderHorizontalBars(title: string, labels: string[], values: number[], color: string): string {
  if (!values.length) return '';
  const width = 360;
  const height = 210;
  const chartLeft = 130;
  const chartTop = 18;
  const chartWidth = 190;
  const rowHeight = 24;
  const max = Math.max(...values) || 1;

  const bars = values.slice(0, 5).map((value, index) => {
    const y = chartTop + index * rowHeight;
    const barWidth = (value / max) * chartWidth;
    return `
      <text x="${chartLeft - 8}" y="${y + 14}" font-size="9" fill="#475569" text-anchor="end">${escapeHtml(truncate(labels[index] || '', 20))}</text>
      <rect x="${chartLeft}" y="${y + 3}" width="${barWidth}" height="14" rx="4" fill="${color}" />
    `;
  });

  return `
    <div class="chart-card">
      <div class="chart-title">${escapeHtml(title)}</div>
      <svg viewBox="0 0 ${width} ${height}" class="chart-svg">
        ${bars.join('')}
      </svg>
    </div>`;
}

function renderDonutChart(title: string, labels: string[], values: number[]): string {
  if (!values.length) return '';
  const total = values.reduce((sum, value) => sum + value, 0) || 1;
  const centerX = 110;
  const centerY = 90;
  const radius = 52;
  const innerRadius = 28;

  let cumulative = 0;
  const segments = values.slice(0, 5).map((value, index) => {
    const startAngle = (cumulative / total) * Math.PI * 2 - Math.PI / 2;
    cumulative += value;
    const endAngle = (cumulative / total) * Math.PI * 2 - Math.PI / 2;
    const x1 = centerX + radius * Math.cos(startAngle);
    const y1 = centerY + radius * Math.sin(startAngle);
    const x2 = centerX + radius * Math.cos(endAngle);
    const y2 = centerY + radius * Math.sin(endAngle);
    const largeArc = endAngle - startAngle > Math.PI ? 1 : 0;
    return `<path d="M ${centerX} ${centerY} L ${x1} ${y1} A ${radius} ${radius} 0 ${largeArc} 1 ${x2} ${y2} Z" fill="${CHART_COLORS[index % CHART_COLORS.length]}" />`;
  });

  const legend = labels.slice(0, 5).map((label, index) => {
    const y = 34 + index * 20;
    return `
      <rect x="210" y="${y - 8}" width="10" height="10" rx="2" fill="${CHART_COLORS[index % CHART_COLORS.length]}" />
      <text x="226" y="${y}" font-size="9" fill="#475569">${escapeHtml(truncate(label, 18))}</text>
    `;
  });

  return `
    <div class="chart-card">
      <div class="chart-title">${escapeHtml(title)}</div>
      <svg viewBox="0 0 360 210" class="chart-svg">
        ${segments.join('')}
        <circle cx="${centerX}" cy="${centerY}" r="${innerRadius}" fill="#ffffff" />
        <text x="${centerX}" y="${centerY - 2}" text-anchor="middle" font-size="10" font-weight="700" fill="#0f172a">Breakdown</text>
        <text x="${centerX}" y="${centerY + 12}" text-anchor="middle" font-size="8.5" fill="#64748b">${values.length} items</text>
        ${legend.join('')}
      </svg>
    </div>`;
}

function renderBenchmark(benchmark: BenchmarkData | null | undefined, labels: Labels): string {
  if (!benchmark) return '';
  const max = Math.max(benchmark.topPerformers, benchmark.industryAverage, benchmark.yourMetric, 1);
  const yourWidth = (benchmark.yourMetric / max) * 100;
  const avgWidth = (benchmark.industryAverage / max) * 100;
  const topWidth = (benchmark.topPerformers / max) * 100;

  return `
    <div class="section-block">
      <div class="section-title">${escapeHtml(labels.benchmark)}</div>
      <div class="benchmark-card">
        <div class="benchmark-status">${escapeHtml(benchmark.metricName)}</div>
        <div class="benchmark-row">
          <span>${escapeHtml(labels.benchmarkLabels.yourBusiness)}</span>
          <strong>${benchmark.yourMetric}${escapeHtml(benchmark.unit)}</strong>
        </div>
        <div class="benchmark-bar"><span style="width:${yourWidth}%"></span></div>
        <div class="benchmark-row">
          <span>${escapeHtml(labels.benchmarkLabels.industryAverage)}</span>
          <strong>${benchmark.industryAverage}${escapeHtml(benchmark.unit)}</strong>
        </div>
        <div class="benchmark-bar secondary"><span style="width:${avgWidth}%"></span></div>
        <div class="benchmark-row">
          <span>${escapeHtml(labels.benchmarkLabels.topPerformers)}</span>
          <strong>${benchmark.topPerformers}${escapeHtml(benchmark.unit)}</strong>
        </div>
        <div class="benchmark-bar success"><span style="width:${topWidth}%"></span></div>
      </div>
    </div>`;
}

function buildReportHTML(insights: BusinessInsights, language: Language, benchmark?: BenchmarkData | null): string {
  const labels = LABELS[language];
  const severity = severityStyle(insights.severity);
  const severityLabel = labels.severity[insights.severity || 'info'];
  const recommendations = [...(insights.recommendations || [])].sort((a, b) => a.priority - b.priority);
  const alerts = insights.alerts || [];
  const chartData = insights.chartData;
  const date = new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });

  const insightSections = [
    {
      title: labels.sections.profit,
      icon: '💰',
      body: [clean(insights.trueProfitAnalysis)].filter(Boolean),
    },
    {
      title: labels.sections.products,
      icon: '⚠️',
      body: (insights.lossMakingProducts || []).map(clean).filter(Boolean),
    },
    {
      title: labels.sections.inventory,
      icon: '📦',
      body: [clean(insights.blockedInventoryCash)].filter(Boolean),
    },
    {
      title: labels.sections.expenses,
      icon: '💸',
      body: (insights.abnormalExpenses || []).map(clean).filter(Boolean),
    },
    {
      title: labels.sections.cashflow,
      icon: '📊',
      body: [clean(insights.cashflowForecast)].filter(Boolean),
    },
  ].filter((section) => section.body.length > 0);

  const pageTwoSections = insightSections.slice(0, 3);
  const pageThreeSections = insightSections.slice(3);

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8" />
  <style>
    * { box-sizing: border-box; }
    body {
      margin: 0;
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      background: #ffffff;
      color: #1e293b;
    }
    .page {
      width: 794px;
      min-height: 1123px;
      padding: 32px 38px 26px;
      display: flex;
      flex-direction: column;
      page-break-after: always;
    }
    .page:last-child { page-break-after: auto; }
    .page-content {
      flex: 1;
    }
    .hero {
      background:
        radial-gradient(circle at top right, rgba(96, 165, 250, 0.28), transparent 30%),
        linear-gradient(135deg, #0f172a 0%, #1d4ed8 55%, #1e40af 100%);
      border-radius: 24px;
      padding: 28px 30px;
      color: #ffffff;
      margin-bottom: 24px;
      position: relative;
      overflow: hidden;
      box-shadow: 0 18px 40px rgba(15, 23, 42, 0.14);
    }
    .hero::after {
      content: "";
      position: absolute;
      right: -48px;
      bottom: -60px;
      width: 220px;
      height: 220px;
      border-radius: 999px;
      background: rgba(255,255,255,0.06);
    }
    .hero-topline {
      display: inline-block;
      margin-bottom: 14px;
      padding: 7px 12px;
      border-radius: 999px;
      background: rgba(255,255,255,0.08);
      border: 1px solid rgba(255,255,255,0.12);
      font-size: 10px;
      font-weight: 700;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      color: rgba(255,255,255,0.88);
    }
    .hero h1 {
      margin: 0 0 6px;
      font-size: 30px;
      line-height: 1.15;
      font-weight: 800;
      letter-spacing: -0.03em;
    }
    .hero p {
      margin: 0 0 12px;
      font-size: 13px;
      line-height: 1.6;
      color: rgba(255,255,255,0.82);
      max-width: 560px;
    }
    .hero-meta {
      display: flex;
      gap: 10px;
      flex-wrap: wrap;
      position: relative;
      z-index: 1;
    }
    .meta-pill {
      padding: 7px 12px;
      border-radius: 999px;
      font-size: 11px;
      font-weight: 700;
      background: rgba(255,255,255,0.08);
      border: 1px solid rgba(255,255,255,0.14);
      color: rgba(255,255,255,0.92);
    }
    .section-block { margin-top: 18px; }
    .section-block:first-child { margin-top: 0; }
    .section-title {
      margin: 0 0 12px;
      font-size: 18px;
      font-weight: 800;
      letter-spacing: -0.02em;
      color: #0f172a;
    }
    .alert-list, .rec-list, .insight-list {
      display: flex;
      flex-direction: column;
      gap: 12px;
    }
    .alert-card, .rec-card, .insight-card {
      border-radius: 18px;
      border: 1px solid #e2e8f0;
      background: #ffffff;
      padding: 16px 18px;
      box-shadow: 0 8px 28px rgba(15, 23, 42, 0.04);
    }
    .alert-card {
      background: ${severity.bg};
      border-color: ${severity.border};
    }
    .alert-card strong {
      display: block;
      font-size: 13px;
      margin-bottom: 4px;
      color: ${severity.text};
    }
    .alert-card p {
      margin: 0;
      font-size: 12px;
      line-height: 1.6;
      color: #475569;
    }
    .rec-card {
      padding: 18px 20px;
    }
    .rec-priority {
      display: inline-block;
      margin-bottom: 8px;
      padding: 6px 10px;
      border-radius: 999px;
      font-size: 11px;
      font-weight: 800;
      background: #eff6ff;
      color: #2563eb;
    }
    .rec-title {
      margin: 0 0 6px;
      font-size: 18px;
      font-weight: 700;
      color: #0f172a;
      line-height: 1.35;
    }
    .rec-impact {
      font-size: 12px;
      line-height: 1.6;
      color: #64748b;
      margin: 0;
    }
    .chart-grid {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 16px;
    }
    .chart-card {
      border-radius: 18px;
      border: 1px solid #e2e8f0;
      background: #ffffff;
      padding: 16px;
      box-shadow: 0 8px 28px rgba(15, 23, 42, 0.04);
      min-height: 250px;
    }
    .chart-title {
      font-size: 15px;
      font-weight: 800;
      color: #0f172a;
      margin-bottom: 10px;
    }
    .chart-svg {
      width: 100%;
      height: 205px;
      display: block;
    }
    .benchmark-card {
      border-radius: 18px;
      border: 1px solid #e2e8f0;
      background: #ffffff;
      padding: 18px;
      box-shadow: 0 8px 28px rgba(15, 23, 42, 0.04);
    }
    .benchmark-status {
      font-size: 16px;
      font-weight: 800;
      color: #2563eb;
      margin-bottom: 14px;
    }
    .benchmark-row {
      display: flex;
      justify-content: space-between;
      font-size: 13px;
      color: #475569;
      margin-bottom: 6px;
    }
    .benchmark-row strong {
      color: #0f172a;
      font-size: 15px;
    }
    .benchmark-bar {
      height: 12px;
      border-radius: 999px;
      background: #e2e8f0;
      overflow: hidden;
      margin-bottom: 12px;
    }
    .benchmark-bar span {
      display: block;
      height: 100%;
      border-radius: 999px;
      background: linear-gradient(90deg, #3b82f6, #1d4ed8);
    }
    .benchmark-bar.secondary span {
      background: linear-gradient(90deg, #f59e0b, #d97706);
    }
    .benchmark-bar.success span {
      background: linear-gradient(90deg, #22c55e, #16a34a);
    }
    .insight-card h3 {
      margin: 0 0 10px;
      font-size: 22px;
      font-weight: 800;
      color: #0f172a;
      letter-spacing: -0.02em;
    }
    .insight-card ul {
      margin: 0;
      padding-left: 20px;
    }
    .insight-card li, .insight-card p {
      font-size: 15px;
      line-height: 1.72;
      color: #334155;
      margin: 0 0 10px;
    }
    .insight-card p:last-child, .insight-card li:last-child { margin-bottom: 0; }
    .footer {
      margin-top: 18px;
      padding-top: 12px;
      border-top: 1px solid #e2e8f0;
      display: flex;
      justify-content: space-between;
      font-size: 11px;
      color: #94a3b8;
    }
    .empty {
      font-size: 13px;
      color: #64748b;
      padding: 18px;
      border-radius: 16px;
      background: #f8fafc;
      border: 1px dashed #cbd5e1;
    }
  </style>
</head>
<body>
  <div class="page">
    <div class="page-content">
      <div class="hero">
        <div class="hero-topline">Vyapar AI • Analysis Export</div>
        <h1>${escapeHtml(labels.title)}</h1>
        <p>${escapeHtml(labels.subtitle)}</p>
        <div class="hero-meta">
          <span class="meta-pill">${escapeHtml(labels.generatedOn)}: ${escapeHtml(date)}</span>
          <span class="meta-pill">${escapeHtml(severityLabel)}</span>
          <span class="meta-pill">${escapeHtml(labels.visualAnalysis)}</span>
        </div>
      </div>

      <div class="section-block">
        <h2 class="section-title">${escapeHtml(labels.alerts)}</h2>
        ${
          alerts.length
            ? `<div class="alert-list">${alerts
                .slice(0, 4)
                .map(
                  (alert) => `
                  <div class="alert-card">
                    <strong>${escapeHtml(alert.icon)} ${escapeHtml(labels.severity[alert.severity])}</strong>
                    <p>${escapeHtml(clean(alert.message))}</p>
                  </div>`
                )
                .join('')}</div>`
            : `<div class="empty">${escapeHtml(labels.noData)}</div>`
        }
      </div>

      <div class="section-block">
        <h2 class="section-title">${escapeHtml(labels.recommendations)}</h2>
        ${
          recommendations.length
            ? `<div class="rec-list">${recommendations
                .map(
                  (rec) => `
                  <div class="rec-card">
                    <div class="rec-priority">${escapeHtml(labels.severity[rec.severity])} • ${escapeHtml(String(rec.priority))}</div>
                    <h3 class="rec-title">${escapeHtml(clean(rec.action))}</h3>
                    <p class="rec-impact">${escapeHtml(clean(rec.impact))}</p>
                  </div>`
                )
                .join('')}</div>`
            : `<div class="empty">${escapeHtml(labels.noData)}</div>`
        }
      </div>
    </div>

    <div class="footer">
      <span>${escapeHtml(labels.footer)}</span>
      <span>${escapeHtml(labels.pageLabel)} 1</span>
    </div>
  </div>

  <div class="page">
    <div class="page-content">
      <div class="section-block">
        <h2 class="section-title">${escapeHtml(labels.visualAnalysis)}</h2>
        <div class="chart-grid">
          ${
            chartData?.profitTrend
              ? renderLineChart('Profit Trend', chartData.profitTrend.labels, chartData.profitTrend.values)
              : `<div class="empty">${escapeHtml(labels.noData)}</div>`
          }
          ${
            chartData?.productSales
              ? renderVerticalBars('Product Sales', chartData.productSales.labels, chartData.productSales.values, '#10b981')
              : `<div class="empty">${escapeHtml(labels.noData)}</div>`
          }
          ${
            chartData?.expenseBreakdown
              ? renderDonutChart('Expense Breakdown', chartData.expenseBreakdown.labels, chartData.expenseBreakdown.values)
              : `<div class="empty">${escapeHtml(labels.noData)}</div>`
          }
          ${
            chartData?.inventoryValue
              ? renderHorizontalBars('Inventory Value', chartData.inventoryValue.labels, chartData.inventoryValue.values, '#f59e0b')
              : `<div class="empty">${escapeHtml(labels.noData)}</div>`
          }
        </div>
      </div>

      ${renderBenchmark(benchmark, labels)}
    </div>

    <div class="footer">
      <span>${escapeHtml(labels.footer)}</span>
      <span>${escapeHtml(labels.pageLabel)} 2</span>
    </div>
  </div>

  <div class="page">
    <div class="page-content">
      <div class="section-block">
        <h2 class="section-title">${escapeHtml(labels.insights)}</h2>
        <div class="insight-list">
          ${pageTwoSections
            .map(
              (section) => `
              <div class="insight-card">
                <h3>${escapeHtml(section.icon)} ${escapeHtml(section.title)}</h3>
                ${
                  section.body.length === 1
                    ? `<p>${escapeHtml(section.body[0])}</p>`
                    : `<ul>${section.body.map((item) => `<li>${escapeHtml(item)}</li>`).join('')}</ul>`
                }
              </div>`
            )
            .join('')}
        </div>
      </div>
    </div>

    <div class="footer">
      <span>${escapeHtml(labels.footer)}</span>
      <span>${escapeHtml(labels.pageLabel)} 3</span>
    </div>
  </div>

  ${
    pageThreeSections.length
      ? `<div class="page">
        <div class="page-content">
          <div class="section-block">
            <h2 class="section-title">${escapeHtml(labels.insights)}</h2>
            <div class="insight-list">
              ${pageThreeSections
                .map(
                  (section) => `
                  <div class="insight-card">
                    <h3>${escapeHtml(section.icon)} ${escapeHtml(section.title)}</h3>
                    ${
                      section.body.length === 1
                        ? `<p>${escapeHtml(section.body[0])}</p>`
                        : `<ul>${section.body.map((item) => `<li>${escapeHtml(item)}</li>`).join('')}</ul>`
                    }
                  </div>`
                )
                .join('')}
            </div>
          </div>
        </div>

        <div class="footer">
          <span>${escapeHtml(labels.footer)}</span>
          <span>${escapeHtml(labels.pageLabel)} 4</span>
        </div>
      </div>`
      : ''
  }
</body>
</html>`;
}

export default function ExportPDF({ insights, language, benchmark }: ExportPDFProps) {
  const handleExport = async () => {
    const [{ default: jsPDF }, { default: html2canvas }] = await Promise.all([
      import('jspdf'),
      import('html2canvas'),
    ]);

    const html = buildReportHTML(insights, language, benchmark);
    const iframe = document.createElement('iframe');
    iframe.style.cssText =
      'position:fixed;top:-9999px;left:-9999px;width:794px;height:1123px;border:none;background:white;';
    document.body.appendChild(iframe);

    const iframeDoc = iframe.contentDocument || iframe.contentWindow?.document;
    if (!iframeDoc) {
      document.body.removeChild(iframe);
      return;
    }

    iframeDoc.open();
    iframeDoc.write(html);
    iframeDoc.close();

    await new Promise((resolve) => setTimeout(resolve, 400));

    const pdf = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'portrait' });
    const pdfWidth = pdf.internal.pageSize.getWidth();
    const pageNodes = Array.from(iframeDoc.querySelectorAll('.page'));

    for (let index = 0; index < pageNodes.length; index += 1) {
      const pageNode = pageNodes[index] as HTMLElement;
      const canvas = await html2canvas(pageNode, {
        scale: 2,
        useCORS: true,
        backgroundColor: '#ffffff',
        width: 794,
        windowWidth: 794,
      });

      if (index > 0) {
        pdf.addPage();
      }

      const imageData = canvas.toDataURL('image/png');
      const imageHeight = (canvas.height * pdfWidth) / canvas.width;
      pdf.addImage(imageData, 'PNG', 0, 0, pdfWidth, imageHeight);
    }

    document.body.removeChild(iframe);

    const filename =
      language === 'hi'
        ? 'vyapar-business-report-hi.pdf'
        : language === 'mr'
        ? 'vyapar-business-report-mr.pdf'
        : 'vyapar-business-report.pdf';

    pdf.save(filename);
  };

  return (
    <Button
      onClick={handleExport}
      variant="secondary"
      fullWidth
      className="border-primary-200 text-primary-700 hover:bg-primary-50"
    >
      <span className="text-2xl">📥</span>
      <span>{LABELS[language].buttonText}</span>
    </Button>
  );
}
