/**
 * Property-Based Tests for Password Hasher Service
 * 
 * Tests universal correctness properties using fast-check
 * 
 * **Validates: Requirements 11.5, 11.6, 11.2**
 */

import * as fc from 'fast-check';
import { PasswordHasher } from '../password-hasher';

describe('PasswordHasher - Property-Based Tests', () => {
  /**
   * Property 6: Password Verification Correctness
   * 
   * For any valid password, hashing then verifying with the same password 
   * should return true (the hash/verify round-trip preserves correctness).
   * 
   * **Validates: Requirements 11.5**
   */
  test('Property 6: Password Verification Correctness', async () => {
    await fc.assert(
      fc.asyncProperty(
        fc.string({ minLength: 1, maxLength: 100 }),
        async (password) => {
          const hashResult = await PasswordHasher.hash(password);
          
          // Only test if hashing succeeded
          if (!hashResult.success || !hashResult.hash) {
            return true; // Skip invalid inputs
          }
          
          const verifyResult = await PasswordHasher.verify(password, hashResult.hash);
          
          expect(verifyResult.success).toBe(true);
          expect(verifyResult.match).toBe(true);
        }
      ),
      { numRuns: 20 }
    );
  }, 30000); // 30 second timeout for bcrypt operations

  /**
   * Property 7: Password Verification Security
   * 
   * For any valid password, hashing then verifying with a different password 
   * should return false (the hash function provides security).
   * 
   * **Validates: Requirements 11.6**
   */
  test('Property 7: Password Verification Security', async () => {
    await fc.assert(
      fc.asyncProperty(
        fc.string({ minLength: 1, maxLength: 100 }),
        fc.string({ minLength: 1, maxLength: 100 }),
        async (password1, password2) => {
          // Only test when passwords are different
          fc.pre(password1 !== password2);
          
          const hashResult = await PasswordHasher.hash(password1);
          
          // Only test if hashing succeeded
          if (!hashResult.success || !hashResult.hash) {
            return true; // Skip invalid inputs
          }
          
          const verifyResult = await PasswordHasher.verify(password2, hashResult.hash);
          
          expect(verifyResult.success).toBe(true);
          expect(verifyResult.match).toBe(false);
        }
      ),
      { numRuns: 20 }
    );
  }, 30000); // 30 second timeout for bcrypt operations

  /**
   * Property 8: Bcrypt Salt Rounds Configuration
   * 
   * For any password hash generated by the system, the hash string should 
   * indicate 10 salt rounds (format: "$2a$10$" or "$2b$10$").
   * 
   * **Validates: Requirements 11.2**
   */
  test('Property 8: Bcrypt Salt Rounds Configuration', async () => {
    await fc.assert(
      fc.asyncProperty(
        fc.string({ minLength: 1, maxLength: 100 }),
        async (password) => {
          const hashResult = await PasswordHasher.hash(password);
          
          // Only test if hashing succeeded
          if (!hashResult.success || !hashResult.hash) {
            return true; // Skip invalid inputs
          }
          
          // Bcrypt hash format: $2a$10$ or $2b$10$ (10 salt rounds)
          expect(hashResult.hash).toMatch(/^\$2[aby]\$10\$/);
        }
      ),
      { numRuns: 20 }
    );
  }, 30000); // 30 second timeout for bcrypt operations
});
