#!/usr/bin/env python3
"""Appends sendWelcomeEmail to lib/ses-email.ts"""

lines = [
    "",
    "// --- Welcome Email ---",
    "",
    "export async function sendWelcomeEmail(params: {",
    "  to: string;",
    "  username: string;",
    "  shopName: string;",
    "  loginUrl: string;",
    "}): Promise<void> {",
    "  if (!isEmailConfigured()) {",
    "    logger.warn('[SES] EMAIL_FROM_ADDRESS/APP_BASE_URL not set; skipping welcome email', { to: params.to });",
    "    return;",
    "  }",
    "",
    "  const logoUrl = APP_BASE_URL + '/background-removed.png';",
    "  const subject = 'Welcome to Vyapar AI - Your shop is ready!';",
    "",
    "  const textBody = [",
    "    'Hi ' + params.username + ',',",
    "    '',",
    "    'Welcome to Vyapar AI! Your account for ' + params.shopName + ' is all set.',",
    "    '',",
    "    'What you can do:',",
    "    '- Track daily sales and expenses',",
    "    '- Manage credit (Udhaar) and follow up on overdue payments',",
    "    '- Upload receipts or CSV files for instant insights',",
    "    '- Get AI-powered explanations of your financial health',",
    "    '',",
    "    'Log in here: ' + params.loginUrl,",
    "    '',",
    "    '-- Vyapar AI Team',",
    "  ].join('\\n');",
    "",
    "  const htmlBody = [",
    "    '<!DOCTYPE html><html lang=\"en\">',",
    "    '<head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0\"></head>',",
    "    '<body style=\"margin:0;padding:0;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Arial,sans-serif;background-color:#f3f4f8;\">',",
    "    '<table role=\"presentation\" style=\"width:100%;border-collapse:collapse;background-color:#f3f4f8;\">',",
    "    '<tr><td align=\"center\" style=\"padding:40px 20px;\">',",
    "    '<table role=\"presentation\" style=\"max-width:600px;width:100%;border-collapse:collapse;background-color:#ffffff;border-radius:16px;box-shadow:0 4px 24px rgba(11,26,125,0.12);\">',",
    "    emailHeader(logoUrl),",
    "    '<tr><td style=\"padding:36px 30px;\">',",
    "    '<h2 style=\"margin:0 0 6px;color:#0b1a7d;font-size:22px;font-weight:700;\">Welcome, ' + params.username + '!</h2>',",
    "    '<div style=\"width:40px;height:3px;background:#c9a227;border-radius:2px;margin:0 0 20px;\"></div>',",
    "    '<p style=\"margin:0 0 20px;color:#4a4c4e;font-size:15px;line-height:1.7;\">Your <strong style=\"color:#0b1a7d;\">Vyapar AI</strong> account for <strong>' + params.shopName + '</strong> is all set. Start managing your business smarter today.</p>',",
    "    '<table role=\"presentation\" style=\"width:100%;border-collapse:collapse;background:#f5f6ff;border-radius:10px;margin:0 0 24px;\">',",
    "    '<tr><td style=\"padding:20px 24px;\">',",
    "    '<p style=\"margin:0 0 12px;color:#0b1a7d;font-size:13px;font-weight:700;text-transform:uppercase;letter-spacing:0.5px;\">What you can do with Vyapar AI</p>',",
    "    '<ul style=\"margin:0;padding-left:20px;color:#4a4c4e;font-size:14px;line-height:2;\">',",
    "    '<li>Track daily sales and expenses</li>',",
    "    '<li>Manage credit (Udhaar) and follow up on overdue payments</li>',",
    "    '<li>Upload receipts or CSV files for instant insights</li>',",
    "    '<li>Get AI-powered explanations of your financial health</li>',",
    "    '</ul>',",
    "    '</td></tr></table>',",
    "    '<table role=\"presentation\" style=\"border-collapse:collapse;\">',",
    "    '<tr><td style=\"border-radius:10px;background:linear-gradient(135deg,#c9a227 0%,#e8c547 100%);\">',",
    "    '<a href=\"' + params.loginUrl + '\" style=\"display:inline-block;padding:14px 36px;color:#1a1c1d;text-decoration:none;font-size:15px;font-weight:700;border-radius:10px;letter-spacing:0.3px;\">Go to Vyapar AI &rarr;</a>',",
    "    '</td></tr></table>',",
    "    '</td></tr>',",
    "    emailFooter(),",
    "    '</table>',",
    "    '</td></tr></table></body></html>',",
    "  ].join('\\n');",
    "",
    "  try {",
    "    await makeSesClient().send(new SendEmailCommand({",
    "      Source: EMAIL_FROM_ADDRESS!,",
    "      Destination: { ToAddresses: [params.to] },",
    "      Message: {",
    "        Subject: { Data: subject, Charset: 'UTF-8' },",
    "        Body: {",
    "          Text: { Data: textBody, Charset: 'UTF-8' },",
    "          Html: { Data: htmlBody, Charset: 'UTF-8' },",
    "        },",
    "      },",
    "    }));",
    "    logger.info('[SES] Welcome email sent', { to: params.to });",
    "  } catch (error) {",
    "    logger.error('[SES] Failed to send welcome email', { error, to: params.to });",
    "  }",
    "}",
    "",
]

with open('lib/ses-email.ts', 'a') as f:
    f.write('\n'.join(lines))

count = len(open('lib/ses-email.ts').readlines())
print(f'Done. File now has {count} lines.')
