#!/bin/bash

# Vyapar AI - Automated EC2 Deployment Script
# This script automates the deployment process on EC2 with Nginx

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Functions
print_success() {
    echo -e "${GREEN}✓ $1${NC}"
}

print_error() {
    echo -e "${RED}✗ $1${NC}"
}

print_info() {
    echo -e "${YELLOW}ℹ $1${NC}"
}

print_header() {
    echo ""
    echo "================================"
    echo "$1"
    echo "================================"
}

# Check if running as root
if [ "$EUID" -eq 0 ]; then 
    print_error "Please do not run this script as root"
    exit 1
fi

print_header "Vyapar AI - EC2 Deployment"

# Step 1: Check prerequisites
print_header "Step 1: Checking Prerequisites"

# Check if git is installed
if ! command -v git &> /dev/null; then
    print_error "Git is not installed"
    exit 1
fi
print_success "Git is installed"

# Check if nginx is installed
if ! command -v nginx &> /dev/null; then
    print_error "Nginx is not installed. Installing..."
    sudo apt-get update
    sudo apt-get install -y nginx
    print_success "Nginx installed"
else
    print_success "Nginx is installed"
fi

# Step 2: Install Node.js
print_header "Step 2: Installing Node.js"

if ! command -v node &> /dev/null; then
    print_info "Installing Node.js 18.x..."
    curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
    sudo apt-get install -y nodejs
    print_success "Node.js installed"
else
    NODE_VERSION=$(node --version)
    print_success "Node.js is already installed: $NODE_VERSION"
fi

# Step 3: Install PM2
print_header "Step 3: Installing PM2"

if ! command -v pm2 &> /dev/null; then
    print_info "Installing PM2..."
    sudo npm install -g pm2
    print_success "PM2 installed"
else
    PM2_VERSION=$(pm2 --version)
    print_success "PM2 is already installed: $PM2_VERSION"
fi

# Step 4: Setup Application
print_header "Step 4: Setting Up Application"

# Get current directory
APP_DIR=$(pwd)
print_info "Application directory: $APP_DIR"

# Install dependencies
print_info "Installing dependencies..."
npm install
print_success "Dependencies installed"

# Step 5: Configure Environment
print_header "Step 5: Configuring Environment"

if [ ! -f ".env.local" ]; then
    if [ -f ".env.local.example" ]; then
        print_info "Creating .env.local from example..."
        cp .env.local.example .env.local
        print_success ".env.local created"
        print_info "Please edit .env.local with your production values"
        read -p "Press enter to continue after editing .env.local..."
    else
        print_error ".env.local.example not found"
        exit 1
    fi
else
    print_success ".env.local already exists"
fi

# Step 6: Build Application
print_header "Step 6: Building Application"

print_info "Building Next.js application..."
npm run build
print_success "Application built successfully"

# Step 7: Setup PM2
print_header "Step 7: Setting Up PM2"

# Stop existing PM2 process if running
if pm2 list | grep -q "vyapar-ai"; then
    print_info "Stopping existing PM2 process..."
    pm2 delete vyapar-ai
fi

# Start application with PM2
print_info "Starting application with PM2..."
pm2 start npm --name "vyapar-ai" -- start

# Save PM2 configuration
pm2 save

# Setup PM2 startup script
print_info "Setting up PM2 startup script..."
sudo env PATH=$PATH:/usr/bin pm2 startup systemd -u $USER --hp $HOME

print_success "PM2 configured successfully"

# Step 8: Configure Nginx
print_header "Step 8: Configuring Nginx"

# Ask for domain name
read -p "Enter your domain name (or press enter to use IP address): " DOMAIN_NAME

if [ -z "$DOMAIN_NAME" ]; then
    DOMAIN_NAME=$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4)
    print_info "Using IP address: $DOMAIN_NAME"
fi

# Create Nginx configuration
NGINX_CONFIG="/etc/nginx/sites-available/vyapar-ai"

print_info "Creating Nginx configuration..."

sudo tee $NGINX_CONFIG > /dev/null <<EOF
# Vyapar AI - Nginx Configuration
# Generated by deployment script

server {
    listen 80;
    server_name $DOMAIN_NAME;
    
    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    
    # Gzip compression
    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_types text/plain text/css text/xml text/javascript application/x-javascript application/xml+rss application/json application/javascript;
    
    # Client body size limit (must be >= BODY_SIZE_LIMITS.UPLOAD in lib/error-utils.ts)
    client_max_body_size 55M;
    
    # Proxy to Next.js
    location / {
        proxy_pass http://localhost:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;
        
        # Timeouts
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }
    
    # Static files caching
    location /_next/static {
        proxy_pass http://localhost:3000;
        add_header Cache-Control "public, max-age=3600, immutable";
    }
}
EOF

# Enable site
if [ ! -L "/etc/nginx/sites-enabled/vyapar-ai" ]; then
    sudo ln -s $NGINX_CONFIG /etc/nginx/sites-enabled/vyapar-ai
    print_success "Nginx site enabled"
fi

# Remove default site if exists
if [ -L "/etc/nginx/sites-enabled/default" ]; then
    sudo rm /etc/nginx/sites-enabled/default
    print_info "Default site removed"
fi

# Test Nginx configuration
print_info "Testing Nginx configuration..."
sudo nginx -t

# Reload Nginx
print_info "Reloading Nginx..."
sudo systemctl reload nginx

print_success "Nginx configured successfully"

# Step 9: Configure Firewall
print_header "Step 9: Configuring Firewall"

if command -v ufw &> /dev/null; then
    print_info "Configuring UFW firewall..."
    sudo ufw allow 80/tcp
    sudo ufw allow 443/tcp
    sudo ufw allow 22/tcp
    
    # Enable firewall if not already enabled
    if ! sudo ufw status | grep -q "Status: active"; then
        sudo ufw --force enable
    fi
    
    print_success "Firewall configured"
else
    print_info "UFW not installed, skipping firewall configuration"
fi

# Step 10: Setup SSL (Optional)
print_header "Step 10: SSL Certificate (Optional)"

read -p "Do you want to setup SSL with Let's Encrypt? (y/n): " SETUP_SSL

if [ "$SETUP_SSL" = "y" ] || [ "$SETUP_SSL" = "Y" ]; then
    # Install Certbot
    if ! command -v certbot &> /dev/null; then
        print_info "Installing Certbot..."
        sudo apt-get update
        sudo apt-get install -y certbot python3-certbot-nginx
    fi
    
    print_info "Obtaining SSL certificate..."
    sudo certbot --nginx -d $DOMAIN_NAME
    
    print_success "SSL certificate installed"
else
    print_info "Skipping SSL setup"
fi

# Step 11: Final checks
print_header "Step 11: Final Checks"

# Check PM2 status
print_info "Checking PM2 status..."
pm2 status

# Check Nginx status
print_info "Checking Nginx status..."
sudo systemctl status nginx --no-pager

# Test application
print_info "Testing application..."
sleep 3
if curl -s http://localhost:3000 > /dev/null; then
    print_success "Application is responding"
else
    print_error "Application is not responding"
fi

# Deployment summary
print_header "Deployment Complete!"

echo ""
echo "Application Details:"
echo "  - Name: Vyapar AI"
echo "  - Directory: $APP_DIR"
echo "  - URL: http://$DOMAIN_NAME"
echo "  - PM2 Process: vyapar-ai"
echo ""
echo "Useful Commands:"
echo "  - View logs: pm2 logs vyapar-ai"
echo "  - Restart app: pm2 restart vyapar-ai"
echo "  - Stop app: pm2 stop vyapar-ai"
echo "  - Nginx logs: sudo tail -f /var/log/nginx/error.log"
echo "  - Reload Nginx: sudo systemctl reload nginx"
echo ""
echo "Next Steps:"
echo "  1. Update DNS to point to: $DOMAIN_NAME"
echo "  2. Test the application: http://$DOMAIN_NAME"
echo "  3. Setup monitoring and backups"
echo "  4. Configure AWS CloudWatch"
echo ""

print_success "Deployment completed successfully!"
